BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `EquivalentClasses` (
  `SCUClassID`   INTEGER PRIMARY KEY AUTOINCREMENT,
  `OtherClassID` INTEGER NOT NULL,
  `Status`       INTEGER NOT NULL,
  `EquivID`      INTEGER NOT NULL
);
COMMIT;
