insert into School values(0,'California State University, Bakersfield');
insert into School values(1,'California State University, Channel Islands');
insert into School values(2,'California State University, Chico');
insert into School values(3,'California State University, Dominguez Hills');
insert into School values(4,'California State University, East Bay');
insert into School values(5,'California State University, Fresno');
insert into School values(6,'California State University, Fullerton');
insert into School values(7,'Humboldt State University');
insert into School values(8,'California State University, Long Beach');
insert into School values(9,'California State University, Los Angeles');
insert into School values(10,'California State University Maritime Academy');
insert into School values(11,'California State University, Monterey Bay');
insert into School values(12,'California State University, Northridge');
insert into School values(13,'California State Polytechnic University, Pomona');
insert into School values(14,'California State University, Sacramento');
insert into School values(15,'California State University, San Bernardino');
insert into School values(16,'San Diego State University');
insert into School values(17,'San Francisco State University');
insert into School values(18,'San Jose State University');
insert into School values(19,'California Polytechnic State University, San Luis Obispo');
insert into School values(20,'California State University, San Marcos');
insert into School values(21,'Sonoma State University');
insert into School values(22,'California State University, Stanislaus');