insert into School (Name) values('California State University, Bakersfield');
insert into School (Name) values('California State University, Channel Islands');
insert into School (Name) values('California State University, Chico');
insert into School (Name) values('California State University, Dominguez Hills');
insert into School (Name) values('California State University, East Bay');
insert into School (Name) values('California State University, Fresno');
insert into School (Name) values('California State University, Fullerton');
insert into School (Name) values('Humboldt State University');
insert into School (Name) values('California State University, Long Beach');
insert into School (Name) values('California State University, Los Angeles');
insert into School (Name) values('California State University Maritime Academy');
insert into School (Name) values('California State University, Monterey Bay');
insert into School (Name) values('California State University, Northridge');
insert into School (Name) values('California State Polytechnic University, Pomona');
insert into School (Name) values('California State University, Sacramento');
insert into School (Name) values('California State University, San Bernardino');
insert into School (Name) values('San Diego State University');
insert into School (Name) values('San Francisco State University');
insert into School (Name) values('San Jose State University');
insert into School (Name) values('California Polytechnic State University, San Luis Obispo');
insert into School (Name) values('California State University, San Marcos');
insert into School (Name) values('Sonoma State University');
insert into School (Name) values('California State University, Stanislaus');