insert into LocalCourse (Dept, CourseNum, Title) values('COEN','200','Logic Analysis & Synthesis');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','201','Digital Signal Processing I');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','201E','Digital Signal Processing I and II');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','202','Digital Signal Processing II');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','203','VLSI Design I');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','204','Vlsi Design II');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','207','SoC (System on Chip) Verification');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','208','SoC (System-on-Chip) Formal Verification Techniques');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','210','Computer Architecture');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','225','Secure Coding in C & C++');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','233','Computer Networks');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','234','Network Management');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','239','Network Design Analysis');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','240','Machine Learning');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','241','Cloud Computing');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','243','Internet of Things');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','250','Information Security Management');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','252','Computer Forensics');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','253','Secure Systems Development and Evaluation');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','260','Truth, Deduction, and Computation');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','266','Artificial Intelligence');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','268','Mobile Application Development');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','272','Web Search and Information Retrieval');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','275','Object Oriented Analysis Design Progect');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','278','Advanced Web Programming');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','279','Design & Analysis of Algorithms');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','280','Database Systems');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','281','Pattern Recognition and Data Mining');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','283','Operating Systems');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','285','Software Engineering');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','286','Software Quality Assurance and Testing');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','287','Software Dev Proc Mgmt');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','288','Software Ethics');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','290','Computer Graphics');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','296','Topics in Computer Science and Engineering');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','301','High-Level Synthesis');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','303','Logic Design Using HDL');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','304','Semi-Custom Design with Programmable Devices');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','308','Design for Testability');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','313','Advanced Computer Architecture');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','315','Web Architecture & Protocols');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','317','Distributed Systems');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','329','Network Technology');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','331','Wireless and Mobile Networks');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','332','Wireless/Mobile Multimedia Networks');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','335','High Performance Networking');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','338','Image & Video Compression');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','340','Digital Image Processing I');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','344','Computer Vision I');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','348E','Speech Coding, Speech Recognition and Biometrics Applications of Signal Processing');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','350','Network Security');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','351','Internet & E-Commerce Security');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','379','Advanced Design and Analysis of Algorithms');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','380','Advanced Database Systems');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','383','Advanced Operating Systems');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','385','Formal Methods in Software Engineering');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','386','Software Architecture');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','396','Advanced Topics in Computer Science and Engineering');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','485','Software Engineering Capstone');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','493','Directed Research');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','497','Master's Thesis Res');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','498','Phd Thesis Research');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','499','Independent Study');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','912C','Abstract Data Types & Structures');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','920C','Embedded Systems and Assembly Language');
insert into LocalCourse (Dept, CourseNum, Title) values('COEN','921C','Introduction to Logic Design');