insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','200','Computer Architecture',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','202','Software Systems Engineering',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','203','Software Engineering Management',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','206','Computer Network Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','207','Network Programming and Application',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','208','Network Architecture and Protocols',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','209','Network Security',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','210','Software-defined Networks and Network Functions Virtualization',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','212','System Verification',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','213','Parallel Computing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','214','GPU Architecture and Programming',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','217','Human Computer Interaction',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','219','HCI for Cyber Security',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','220','System Software',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','225','Operating System Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','226','Database Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','227','Distributed Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','235','Mobile Software System Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','236','Mobile Web Application Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','237','Design of E-Commerce Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','240','Advanced Computer Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','242','Embedded Hardware Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','243','Embedded Systems Applications',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','244','Embedded Software',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','245','Embedded Wireless Architecture',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','250','Computerized Robots',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','253','Advanced Bioinformatics Computational Laboratory For Engineers',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','255','Data Mining',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','256','Large-Scale Analytics',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','257','Machine Learning',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','258','Deep Learning',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','264','Advanced Digital and Computing System Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','265','High Speed Digital System Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','266','Big Data Engineering and Analytics',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','270','Information Engineering',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','271','Advanced Java Programming',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','272','Enterprise Software Platforms',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','273','Enterprise Distributed Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','274','Business Intelligence Technologies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','275','Enterprise Application Development',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','276','XML for E-Business',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','277','Smartphone Application Development',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','279','Software Security Technologies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','280','Web UI Design and Development',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','281','Cloud Technologies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','282','Cloud Services',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','283','Virtualization Technologies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','284','Storage and Network Virtualization',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','285','Software Engineering Processes',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','287','Software Quality Assurance and Testing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','289','Cloud Security Engineering',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','292','Int''l Program Studies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','294','Computer Engineering Seminar',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','294A','Cyber Security Seminar',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','295A','Master Project I',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','295B','Master Project II',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','295W','Master Project',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','297','Special Topics in Computer/Software Engineering',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','298','Special Problems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','298I','Computer/Software Engineering Internship',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','299A','Master Thesis I',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CMPE','299B','Master Thesis II',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','200W','Graduate Technical Writing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','216','Geometric Modeling',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','218','Topics in Cloud Computing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','223','Bioinformatics',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','235','User Interface Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','243A','Advanced Numerical Analysis',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','243B','Advanced Topics in Numerical Analysis',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','247','Advanced Computer Architecture',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','249','Distributed Computing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','251A','Object-Oriented Analysis',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','251B','Object-Oriented Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','252','Advanced Programming Language Principles',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','253','Advanced Compiler Design',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','254','Theory of Computation',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','255','Design and Analysis of Algorithms',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','256','Topics in Artificial Intelligence',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','257','Database System Principles',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','258','Computer Communication Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','259','Advanced Parallel Processing',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','262','Randomized Algorithms and Applications',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','265','Cryptography and Computer Security',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','266','Topics in Information Security',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','267','Topics in Database Systems',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','268','Topics in Wireless Mobile Networking',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','274','Topics in XML and Web Intelligence',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','280','Graduate Individual Studies',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','286','Advanced Topics in Computer Science',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','297','Preparation for Writing Project or Thesis',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','298','Master''s Writing Project',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CS','299','Master''s Thesis',18);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','720','Advanced Operating Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','730','Advanced Database Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','745','Computer Networks',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','746','High-Performance Computing',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','775','Introduction to Database Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','780','Application Development for Mobile Devices',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','810','Analysis of Algorithms II',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','820','Natural Language Technologies',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','821','Biomedical Imaging & Analysis',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','825','Advanced Automata Theory',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','830','Advanced Computer Graphics',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','831','Multiplayer Game Develop',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','835','Distributed Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','837','Advanced Sound Synthesis',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','840','Software Metrics and Quality Assurance',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','841','Computer Performance Evaluation',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','842','Advanced Human-Computer Interaction',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','845','Advanced Computer Networks',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','846','Systems Architecture',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','848','Software Engineering',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','849','Search Engines',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','850','Compiler Design',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','856','Advanced Computer Architecture',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','857','Bioinformatics Computing',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','858','Foundations of Biotechnology and Life Sciences',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','864','Multimedia Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','867','Internet Application Design and Development',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','868','Advanced Object Oriented Software Design and Development',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','869','Data Mining',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','870','Computational Discrete Geometry',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','871','Neural Networks',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','872','Pattern Analysis and Machine Intelligence',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','875','Advanced Topics in Database Systems',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','890','Graduate Seminar',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','893','Supervised Industrial Research',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','895','Applied Research Project',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','897','Research',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','898','Masters Thesis',17);
insert into ForeignCourse (Dept, CourseNum, Title, SchoolID) values('CSC','899','Independent Study',17);