insert into LocalCourse values(0,'COEN','200','Logic Analysis & Synthesis');
insert into LocalCourse values(1,'COEN','201','Digital Signal Processing I');
insert into LocalCourse values(2,'COEN','201E','Digital Signal Processing I and II');
insert into LocalCourse values(3,'COEN','202','Digital Signal Processing II');
insert into LocalCourse values(4,'COEN','203','VLSI Design I');
insert into LocalCourse values(5,'COEN','204','Vlsi Design II');
insert into LocalCourse values(6,'COEN','207','SoC (System on Chip) Verification');
insert into LocalCourse values(7,'COEN','208','SoC (System-on-Chip) Formal Verification Techniques');
insert into LocalCourse values(8,'COEN','210','Computer Architecture');
insert into LocalCourse values(9,'COEN','225','Secure Coding in C & C++');
insert into LocalCourse values(10,'COEN','233','Computer Networks');
insert into LocalCourse values(11,'COEN','234','Network Management');
insert into LocalCourse values(12,'COEN','239','Network Design Analysis');
insert into LocalCourse values(13,'COEN','240','Machine Learning');
insert into LocalCourse values(14,'COEN','241','Cloud Computing');
insert into LocalCourse values(15,'COEN','243','Internet of Things');
insert into LocalCourse values(16,'COEN','250','Information Security Management');
insert into LocalCourse values(17,'COEN','252','Computer Forensics');
insert into LocalCourse values(18,'COEN','253','Secure Systems Development and Evaluation');
insert into LocalCourse values(19,'COEN','260','Truth, Deduction, and Computation');
insert into LocalCourse values(20,'COEN','266','Artificial Intelligence');
insert into LocalCourse values(21,'COEN','268','Mobile Application Development');
insert into LocalCourse values(22,'COEN','272','Web Search and Information Retrieval');
insert into LocalCourse values(23,'COEN','275','Object Oriented Analysis Design Progect');
insert into LocalCourse values(24,'COEN','278','Advanced Web Programming');
insert into LocalCourse values(25,'COEN','279','Design & Analysis of Algorithms');
insert into LocalCourse values(26,'COEN','280','Database Systems');
insert into LocalCourse values(27,'COEN','281','Pattern Recognition and Data Mining');
insert into LocalCourse values(28,'COEN','283','Operating Systems');
insert into LocalCourse values(29,'COEN','285','Software Engineering');
insert into LocalCourse values(30,'COEN','286','Software Quality Assurance and Testing');
insert into LocalCourse values(31,'COEN','287','Software Dev Proc Mgmt');
insert into LocalCourse values(32,'COEN','288','Software Ethics');
insert into LocalCourse values(33,'COEN','290','Computer Graphics');
insert into LocalCourse values(34,'COEN','296','Topics in Computer Science and Engineering');
insert into LocalCourse values(35,'COEN','301','High-Level Synthesis');
insert into LocalCourse values(36,'COEN','303','Logic Design Using HDL');
insert into LocalCourse values(37,'COEN','304','Semi-Custom Design with Programmable Devices');
insert into LocalCourse values(38,'COEN','308','Design for Testability');
insert into LocalCourse values(39,'COEN','313','Advanced Computer Architecture');
insert into LocalCourse values(40,'COEN','315','Web Architecture & Protocols');
insert into LocalCourse values(41,'COEN','317','Distributed Systems');
insert into LocalCourse values(42,'COEN','329','Network Technology');
insert into LocalCourse values(43,'COEN','331','Wireless and Mobile Networks');
insert into LocalCourse values(44,'COEN','332','Wireless/Mobile Multimedia Networks');
insert into LocalCourse values(45,'COEN','335','High Performance Networking');
insert into LocalCourse values(46,'COEN','338','Image & Video Compression');
insert into LocalCourse values(47,'COEN','340','Digital Image Processing I');
insert into LocalCourse values(48,'COEN','344','Computer Vision I');
insert into LocalCourse values(49,'COEN','348E','Speech Coding, Speech Recognition and Biometrics Applications of Signal Processing');
insert into LocalCourse values(50,'COEN','350','Network Security');
insert into LocalCourse values(51,'COEN','351','Internet & E-Commerce Security');
insert into LocalCourse values(52,'COEN','379','Advanced Design and Analysis of Algorithms');
insert into LocalCourse values(53,'COEN','380','Advanced Database Systems');
insert into LocalCourse values(54,'COEN','383','Advanced Operating Systems');
insert into LocalCourse values(55,'COEN','385','Formal Methods in Software Engineering');
insert into LocalCourse values(56,'COEN','386','Software Architecture');
insert into LocalCourse values(57,'COEN','396','Advanced Topics in Computer Science and Engineering');
insert into LocalCourse values(58,'COEN','485','Software Engineering Capstone');
insert into LocalCourse values(59,'COEN','493','Directed Research');
insert into LocalCourse values(60,'COEN','497','Masters Thesis Res');
insert into LocalCourse values(61,'COEN','498','Phd Thesis Research');
insert into LocalCourse values(62,'COEN','499','Independent Study');
insert into LocalCourse values(63,'COEN','912C','Abstract Data Types & Structures');
insert into LocalCourse values(64,'COEN','920C','Embedded Systems and Assembly Language');
insert into LocalCourse values(65,'COEN','921C','Introduction to Logic Design');