insert into LocalCourse (Dept, CourseNum, Title)
values('COEN','200','Logic Analysis & Synthesis'),
values('COEN','201','Digital Signal Processing I'),
values('COEN','201E','Digital Signal Processing I and II'),
values('COEN','202','Digital Signal Processing II'),
values('COEN','203','VLSI Design I'),
values('COEN','204','Vlsi Design II'),
values('COEN','207','SoC (System on Chip) Verification'),
values('COEN','208','SoC (System-on-Chip) Formal Verification Techniques'),
values('COEN','210','Computer Architecture'),
values('COEN','225','Secure Coding in C & C++'),
values('COEN','233','Computer Networks'),
values('COEN','234','Network Management'),
values('COEN','239','Network Design Analysis'),
values('COEN','240','Machine Learning'),
values('COEN','241','Cloud Computing'),
values('COEN','243','Internet of Things'),
values('COEN','250','Information Security Management'),
values('COEN','252','Computer Forensics'),
values('COEN','253','Secure Systems Development and Evaluation'),
values('COEN','260','Truth, Deduction, and Computation'),
values('COEN','266','Artificial Intelligence'),
values('COEN','268','Mobile Application Development'),
values('COEN','272','Web Search and Information Retrieval'),
values('COEN','275','Object Oriented Analysis Design Progect'),
values('COEN','278','Advanced Web Programming'),
values('COEN','279','Design & Analysis of Algorithms'),
values('COEN','280','Database Systems'),
values('COEN','281','Pattern Recognition and Data Mining'),
values('COEN','283','Operating Systems'),
values('COEN','285','Software Engineering'),
values('COEN','286','Software Quality Assurance and Testing'),
values('COEN','287','Software Dev Proc Mgmt'),
values('COEN','288','Software Ethics'),
values('COEN','290','Computer Graphics'),
values('COEN','296','Topics in Computer Science and Engineering'),
values('COEN','301','High-Level Synthesis'),
values('COEN','303','Logic Design Using HDL'),
values('COEN','304','Semi-Custom Design with Programmable Devices'),
values('COEN','308','Design for Testability'),
values('COEN','313','Advanced Computer Architecture'),
values('COEN','315','Web Architecture & Protocols'),
values('COEN','317','Distributed Systems'),
values('COEN','329','Network Technology'),
values('COEN','331','Wireless and Mobile Networks'),
values('COEN','332','Wireless/Mobile Multimedia Networks'),
values('COEN','335','High Performance Networking'),
values('COEN','338','Image & Video Compression'),
values('COEN','340','Digital Image Processing I'),
values('COEN','344','Computer Vision I'),
values('COEN','348E','Speech Coding, Speech Recognition and Biometrics Applications of Signal Processing'),
values('COEN','350','Network Security'),
values('COEN','351','Internet & E-Commerce Security'),
values('COEN','379','Advanced Design and Analysis of Algorithms'),
values('COEN','380','Advanced Database Systems'),
values('COEN','383','Advanced Operating Systems'),
values('COEN','385','Formal Methods in Software Engineering'),
values('COEN','386','Software Architecture'),
values('COEN','396','Advanced Topics in Computer Science and Engineering'),
values('COEN','485','Software Engineering Capstone'),
values('COEN','493','Directed Research'),
values('COEN','497','Master''s Thesis Res'),
values('COEN','498','Phd Thesis Research'),
values('COEN','499','Independent Study'),
values('COEN','912C','Abstract Data Types & Structures'),
values('COEN','920C','Embedded Systems and Assembly Language'),
values('COEN','921C','Introduction to Logic Design')