/* SJSU */
insert into ForeignCourse values(0,'CMPE','200','Computer Architecture',18);
insert into ForeignCourse values(1,'CMPE','202','Software Systems Engineering',18);
insert into ForeignCourse values(2,'CMPE','203','Software Engineering Management',18);
insert into ForeignCourse values(3,'CMPE','206','Computer Network Design',18);
insert into ForeignCourse values(4,'CMPE','207','Network Programming and Application',18);
insert into ForeignCourse values(5,'CMPE','208','Network Architecture and Protocols',18);
insert into ForeignCourse values(6,'CMPE','209','Network Security',18);
insert into ForeignCourse values(7,'CMPE','210','Software-defined Networks and Network Functions Virtualization',18);
insert into ForeignCourse values(8,'CMPE','212','System Verification',18);
insert into ForeignCourse values(9,'CMPE','213','Parallel Computing',18);
insert into ForeignCourse values(10,'CMPE','214','GPU Architecture and Programming',18);
insert into ForeignCourse values(11,'CMPE','217','Human Computer Interaction',18);
insert into ForeignCourse values(12,'CMPE','219','HCI for Cyber Security',18);
insert into ForeignCourse values(13,'CMPE','220','System Software',18);
insert into ForeignCourse values(14,'CMPE','225','Operating System Design',18);
insert into ForeignCourse values(15,'CMPE','226','Database Systems',18);
insert into ForeignCourse values(16,'CMPE','227','Distributed Systems',18);
insert into ForeignCourse values(17,'CMPE','235','Mobile Software System Design',18);
insert into ForeignCourse values(18,'CMPE','236','Mobile Web Application Systems',18);
insert into ForeignCourse values(19,'CMPE','237','Design of E-Commerce Systems',18);
insert into ForeignCourse values(20,'CMPE','240','Advanced Computer Design',18);
insert into ForeignCourse values(21,'CMPE','242','Embedded Hardware Design',18);
insert into ForeignCourse values(22,'CMPE','243','Embedded Systems Applications',18);
insert into ForeignCourse values(23,'CMPE','244','Embedded Software',18);
insert into ForeignCourse values(24,'CMPE','245','Embedded Wireless Architecture',18);
insert into ForeignCourse values(25,'CMPE','250','Computerized Robots',18);
insert into ForeignCourse values(26,'CMPE','253','Advanced Bioinformatics Computational Laboratory For Engineers',18);
insert into ForeignCourse values(27,'CMPE','255','Data Mining',18);
insert into ForeignCourse values(28,'CMPE','256','Large-Scale Analytics',18);
insert into ForeignCourse values(29,'CMPE','257','Machine Learning',18);
insert into ForeignCourse values(30,'CMPE','258','Deep Learning',18);
insert into ForeignCourse values(31,'CMPE','264','Advanced Digital and Computing System Design',18);
insert into ForeignCourse values(32,'CMPE','265','High Speed Digital System Design',18);
insert into ForeignCourse values(33,'CMPE','266','Big Data Engineering and Analytics',18);
insert into ForeignCourse values(34,'CMPE','270','Information Engineering',18);
insert into ForeignCourse values(35,'CMPE','271','Advanced Java Programming',18);
insert into ForeignCourse values(36,'CMPE','272','Enterprise Software Platforms',18);
insert into ForeignCourse values(37,'CMPE','273','Enterprise Distributed Systems',18);
insert into ForeignCourse values(38,'CMPE','274','Business Intelligence Technologies',18);
insert into ForeignCourse values(39,'CMPE','275','Enterprise Application Development',18);
insert into ForeignCourse values(40,'CMPE','276','XML for E-Business',18);
insert into ForeignCourse values(41,'CMPE','277','Smartphone Application Development',18);
insert into ForeignCourse values(42,'CMPE','279','Software Security Technologies',18);
insert into ForeignCourse values(43,'CMPE','280','Web UI Design and Development',18);
insert into ForeignCourse values(44,'CMPE','281','Cloud Technologies',18);
insert into ForeignCourse values(45,'CMPE','282','Cloud Services',18);
insert into ForeignCourse values(46,'CMPE','283','Virtualization Technologies',18);
insert into ForeignCourse values(47,'CMPE','284','Storage and Network Virtualization',18);
insert into ForeignCourse values(48,'CMPE','285','Software Engineering Processes',18);
insert into ForeignCourse values(49,'CMPE','287','Software Quality Assurance and Testing',18);
insert into ForeignCourse values(50,'CMPE','289','Cloud Security Engineering',18);
insert into ForeignCourse values(51,'CMPE','292','Intl Program Studies',18);
insert into ForeignCourse values(52,'CMPE','294','Computer Engineering Seminar',18);
insert into ForeignCourse values(53,'CMPE','294A','Cyber Security Seminar',18);
insert into ForeignCourse values(54,'CMPE','295A','Master Project I',18);
insert into ForeignCourse values(55,'CMPE','295B','Master Project II',18);
insert into ForeignCourse values(56,'CMPE','295W','Master Project',18);
insert into ForeignCourse values(57,'CMPE','297','Special Topics in Computer/Software Engineering',18);
insert into ForeignCourse values(58,'CMPE','298','Special Problems',18);
insert into ForeignCourse values(59,'CMPE','298I','Computer/Software Engineering Internship',18);
insert into ForeignCourse values(60,'CMPE','299A','Master Thesis I',18);
insert into ForeignCourse values(61,'CMPE','299B','Master Thesis II',18);
insert into ForeignCourse values(62,'CS','200W','Graduate Technical Writing',18);
insert into ForeignCourse values(63,'CS','216','Geometric Modeling',18);
insert into ForeignCourse values(64,'CS','218','Topics in Cloud Computing',18);
insert into ForeignCourse values(65,'CS','223','Bioinformatics',18);
insert into ForeignCourse values(66,'CS','235','User Interface Design',18);
insert into ForeignCourse values(67,'CS','243A','Advanced Numerical Analysis',18);
insert into ForeignCourse values(68,'CS','243B','Advanced Topics in Numerical Analysis',18);
insert into ForeignCourse values(69,'CS','247','Advanced Computer Architecture',18);
insert into ForeignCourse values(70,'CS','249','Distributed Computing',18);
insert into ForeignCourse values(71,'CS','251A','Object-Oriented Analysis',18);
insert into ForeignCourse values(72,'CS','251B','Object-Oriented Design',18);
insert into ForeignCourse values(73,'CS','252','Advanced Programming Language Principles',18);
insert into ForeignCourse values(74,'CS','253','Advanced Compiler Design',18);
insert into ForeignCourse values(75,'CS','254','Theory of Computation',18);
insert into ForeignCourse values(76,'CS','255','Design and Analysis of Algorithms',18);
insert into ForeignCourse values(77,'CS','256','Topics in Artificial Intelligence',18);
insert into ForeignCourse values(78,'CS','257','Database System Principles',18);
insert into ForeignCourse values(79,'CS','258','Computer Communication Systems',18);
insert into ForeignCourse values(80,'CS','259','Advanced Parallel Processing',18);
insert into ForeignCourse values(81,'CS','262','Randomized Algorithms and Applications',18);
insert into ForeignCourse values(82,'CS','265','Cryptography and Computer Security',18);
insert into ForeignCourse values(83,'CS','266','Topics in Information Security',18);
insert into ForeignCourse values(84,'CS','267','Topics in Database Systems',18);
insert into ForeignCourse values(85,'CS','268','Topics in Wireless Mobile Networking',18);
insert into ForeignCourse values(86,'CS','274','Topics in XML and Web Intelligence',18);
insert into ForeignCourse values(87,'CS','280','Graduate Individual Studies',18);
insert into ForeignCourse values(88,'CS','286','Advanced Topics in Computer Science',18);
insert into ForeignCourse values(89,'CS','297','Preparation for Writing Project or Thesis',18);
insert into ForeignCourse values(90,'CS','298','Masters Writing Project',18);
insert into ForeignCourse values(91,'CS','299','Masters Thesis',18);
/* SFSU */
insert into ForeignCourse values(92,'CSC','720','Advanced Operating Systems',17);
insert into ForeignCourse values(93,'CSC','730','Advanced Database Systems',17);
insert into ForeignCourse values(94,'CSC','745','Computer Networks',17);
insert into ForeignCourse values(95,'CSC','746','High-Performance Computing',17);
insert into ForeignCourse values(96,'CSC','775','Introduction to Database Systems',17);
insert into ForeignCourse values(97,'CSC','780','Application Development for Mobile Devices',17);
insert into ForeignCourse values(98,'CSC','810','Analysis of Algorithms II',17);
insert into ForeignCourse values(99,'CSC','820','Natural Language Technologies',17);
insert into ForeignCourse values(100,'CSC','821','Biomedical Imaging & Analysis',17);
insert into ForeignCourse values(101,'CSC','825','Advanced Automata Theory',17);
insert into ForeignCourse values(102,'CSC','830','Advanced Computer Graphics',17);
insert into ForeignCourse values(103,'CSC','831','Multiplayer Game Develop',17);
insert into ForeignCourse values(104,'CSC','835','Distributed Systems',17);
insert into ForeignCourse values(105,'CSC','837','Advanced Sound Synthesis',17);
insert into ForeignCourse values(106,'CSC','840','Software Metrics and Quality Assurance',17);
insert into ForeignCourse values(107,'CSC','841','Computer Performance Evaluation',17);
insert into ForeignCourse values(108,'CSC','842','Advanced Human-Computer Interaction',17);
insert into ForeignCourse values(109,'CSC','845','Advanced Computer Networks',17);
insert into ForeignCourse values(110,'CSC','846','Systems Architecture',17);
insert into ForeignCourse values(111,'CSC','848','Software Engineering',17);
insert into ForeignCourse values(112,'CSC','849','Search Engines',17);
insert into ForeignCourse values(113,'CSC','850','Compiler Design',17);
insert into ForeignCourse values(114,'CSC','856','Advanced Computer Architecture',17);
insert into ForeignCourse values(115,'CSC','857','Bioinformatics Computing',17);
insert into ForeignCourse values(116,'CSC','858','Foundations of Biotechnology and Life Sciences',17);
insert into ForeignCourse values(117,'CSC','864','Multimedia Systems',17);
insert into ForeignCourse values(118,'CSC','867','Internet Application Design and Development',17);
insert into ForeignCourse values(119,'CSC','868','Advanced Object Oriented Software Design and Development',17);
insert into ForeignCourse values(120,'CSC','869','Data Mining',17);
insert into ForeignCourse values(121,'CSC','870','Computational Discrete Geometry',17);
insert into ForeignCourse values(122,'CSC','871','Neural Networks',17);
insert into ForeignCourse values(123,'CSC','872','Pattern Analysis and Machine Intelligence',17);
insert into ForeignCourse values(124,'CSC','875','Advanced Topics in Database Systems',17);
insert into ForeignCourse values(125,'CSC','890','Graduate Seminar',17);
insert into ForeignCourse values(126,'CSC','893','Supervised Industrial Research',17);
insert into ForeignCourse values(127,'CSC','895','Applied Research Project',17);
insert into ForeignCourse values(128,'CSC','897','Research',17);
insert into ForeignCourse values(129,'CSC','898','Masters Thesis',17);
insert into ForeignCourse values(130,'CSC','899','Independent Study',17);