import { ChangeJoined } from '../models/change_joined';

export const CHANGES: ChangeJoined[] = [
{"LocalCourseName":"COEN 233 - Computer Networks","ForeignCourseName":"CSC 745 - Computer Networks","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 240 - Machine Learning","ForeignCourseName":"CMPE 257 - Machine Learning","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 279 - Design & Analysis of Algorithms","ForeignCourseName":"CS 255 - Design and Analysis of Algorithms","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 280 - Database Systems","ForeignCourseName":"CMPE 226 - Database Systems","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 285 - Software Engineering","ForeignCourseName":"CSC 848 - Software Engineering","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 286 - Software Quality Assurance and Testing","ForeignCourseName":"CMPE 287 - Software Quality Assurance and Testing","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 313 - Advanced Computer Architecture","ForeignCourseName":"CS 247 - Advanced Computer Architecture","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 313 - Advanced Computer Architecture","ForeignCourseName":"CSC 856 - Advanced Computer Architecture","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 317 - Distributed Systems","ForeignCourseName":"CSC 835 - Distributed Systems","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 350 - Network Security","ForeignCourseName":"CMPE 209 - Network Security","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 380 - Advanced Database Systems","ForeignCourseName":"CSC 730 - Advanced Database Systems","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 383 - Advanced Operating Systems","ForeignCourseName":"CSC 720 - Advanced Operating Systems","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 499 - Independent Study","ForeignCourseName":"CSC 899 - Independent Study","SchoolName":"San Francisco State University","NewStatus":"rejected","Notes":"added via recommender system","Date":"2017-10-11 21:11:53","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 210 - Computer Architecture","ForeignCourseName":"CSC 856 - Advanced Computer Architecture","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"","Date":"2017-10-11 12:04:55","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 210 - Computer Architecture","ForeignCourseName":"CMPE 200 - Computer Architecture","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 317 - Distributed Systems","ForeignCourseName":"CMPE 227 - Distributed Systems","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 283 - Operating Systems","ForeignCourseName":"CSC 720 - Advanced Operating Systems","SchoolName":"San Francisco State University","NewStatus":"accepted","Notes":"","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 280 - Database Systems","ForeignCourseName":"CSC 730 - Advanced Database Systems","SchoolName":"San Francisco State University","NewStatus":"rejected","Notes":"","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 268 - Mobile Application Development","ForeignCourseName":"CMPE 236 - Mobile Web Application Systems","SchoolName":"San Jose State University","NewStatus":"accepted","Notes":"course is valid for this version of algorithms","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"},
{"LocalCourseName":"COEN 279 - Design & Analysis of Algorithms","ForeignCourseName":"CSC 810 - Analysis of Algorithms II","SchoolName":"San Francisco State University","NewStatus":"rejected","Notes":"course is invalid for this version of algorithms","Date":"2017-10-10 11:42:54","UserName":"Andrew Leonard","UserEmail":"aleonard@scu.edu"}
];