import { LocalCourseJoined } from '../models/local_course_joined';

export const LOCAL_COURSES_2: LocalCourseJoined[] = [
{"EquivID":null,"Status":null,"LocalCourseID":1,"LocalCourseName":"COEN 200 - Logic Analysis & Synthesis","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":2,"LocalCourseName":"COEN 201 - Digital Signal Processing I","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":3,"LocalCourseName":"COEN 201E - Digital Signal Processing I and II","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":4,"LocalCourseName":"COEN 202 - Digital Signal Processing II","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":5,"LocalCourseName":"COEN 203 - VLSI Design I","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":6,"LocalCourseName":"COEN 204 - Vlsi Design II","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":7,"LocalCourseName":"COEN 207 - SoC (System on Chip) Verification","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":8,"LocalCourseName":"COEN 208 - SoC (System-on-Chip) Formal Verification Techniques","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":1,"Status":"accepted","LocalCourseID":9,"LocalCourseName":"COEN 210 - Computer Architecture","ForeignCourseID":1,"ForeignCourseName":"CMPE 200 - Computer Architecture","SchoolName":"San Jose State University"},
{"EquivID":8,"Status":"accepted","LocalCourseID":9,"LocalCourseName":"COEN 210 - Computer Architecture","ForeignCourseID":115,"ForeignCourseName":"CSC 856 - Advanced Computer Architecture","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":10,"LocalCourseName":"COEN 225 - Secure Coding in C & C++","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":36,"Status":"accepted","LocalCourseID":11,"LocalCourseName":"COEN 233 - Computer Networks","ForeignCourseID":95,"ForeignCourseName":"CSC 745 - Computer Networks","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":12,"LocalCourseName":"COEN 234 - Network Management","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":13,"LocalCourseName":"COEN 239 - Network Design Analysis","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":37,"Status":"accepted","LocalCourseID":14,"LocalCourseName":"COEN 240 - Machine Learning","ForeignCourseID":30,"ForeignCourseName":"CMPE 257 - Machine Learning","SchoolName":"San Jose State University"},
{"EquivID":null,"Status":null,"LocalCourseID":15,"LocalCourseName":"COEN 241 - Cloud Computing","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":16,"LocalCourseName":"COEN 243 - Internet of Things","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":17,"LocalCourseName":"COEN 250 - Information Security Management","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":18,"LocalCourseName":"COEN 252 - Computer Forensics","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":19,"LocalCourseName":"COEN 253 - Secure Systems Development and Evaluation","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":20,"LocalCourseName":"COEN 260 - Truth, Deduction, and Computation","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":21,"LocalCourseName":"COEN 266 - Artificial Intelligence","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":5,"Status":"rejected","LocalCourseID":22,"LocalCourseName":"COEN 268 - Mobile Application Development","ForeignCourseID":19,"ForeignCourseName":"CMPE 236 - Mobile Web Application Systems","SchoolName":"San Jose State University"},
{"EquivID":null,"Status":null,"LocalCourseID":23,"LocalCourseName":"COEN 272 - Web Search and Information Retrieval","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":24,"LocalCourseName":"COEN 275 - Object Oriented Analysis Design Progect","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":25,"LocalCourseName":"COEN 278 - Advanced Web Programming","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":38,"Status":"accepted","LocalCourseID":26,"LocalCourseName":"COEN 279 - Design & Analysis of Algorithms","ForeignCourseID":77,"ForeignCourseName":"CS 255 - Design and Analysis of Algorithms","SchoolName":"San Jose State University"},
{"EquivID":6,"Status":"accepted","LocalCourseID":26,"LocalCourseName":"COEN 279 - Design & Analysis of Algorithms","ForeignCourseID":99,"ForeignCourseName":"CSC 810 - Analysis of Algorithms II","SchoolName":"San Francisco State University"},
{"EquivID":39,"Status":"accepted","LocalCourseID":27,"LocalCourseName":"COEN 280 - Database Systems","ForeignCourseID":16,"ForeignCourseName":"CMPE 226 - Database Systems","SchoolName":"San Jose State University"},
{"EquivID":4,"Status":"accepted","LocalCourseID":27,"LocalCourseName":"COEN 280 - Database Systems","ForeignCourseID":94,"ForeignCourseName":"CSC 730 - Advanced Database Systems","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":28,"LocalCourseName":"COEN 281 - Pattern Recognition and Data Mining","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":3,"Status":"accepted","LocalCourseID":29,"LocalCourseName":"COEN 283 - Operating Systems","ForeignCourseID":93,"ForeignCourseName":"CSC 720 - Advanced Operating Systems","SchoolName":"San Francisco State University"},
{"EquivID":40,"Status":"accepted","LocalCourseID":30,"LocalCourseName":"COEN 285 - Software Engineering","ForeignCourseID":112,"ForeignCourseName":"CSC 848 - Software Engineering","SchoolName":"San Francisco State University"},
{"EquivID":41,"Status":"accepted","LocalCourseID":31,"LocalCourseName":"COEN 286 - Software Quality Assurance and Testing","ForeignCourseID":50,"ForeignCourseName":"CMPE 287 - Software Quality Assurance and Testing","SchoolName":"San Jose State University"},
{"EquivID":null,"Status":null,"LocalCourseID":32,"LocalCourseName":"COEN 287 - Software Dev Proc Mgmt","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":33,"LocalCourseName":"COEN 288 - Software Ethics","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":34,"LocalCourseName":"COEN 290 - Computer Graphics","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":35,"LocalCourseName":"COEN 296 - Topics in Computer Science and Engineering","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":36,"LocalCourseName":"COEN 301 - High-Level Synthesis","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":37,"LocalCourseName":"COEN 303 - Logic Design Using HDL","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":38,"LocalCourseName":"COEN 304 - Semi-Custom Design with Programmable Devices","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":39,"LocalCourseName":"COEN 308 - Design for Testability","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":42,"Status":"accepted","LocalCourseID":40,"LocalCourseName":"COEN 313 - Advanced Computer Architecture","ForeignCourseID":70,"ForeignCourseName":"CS 247 - Advanced Computer Architecture","SchoolName":"San Jose State University"},
{"EquivID":43,"Status":"accepted","LocalCourseID":40,"LocalCourseName":"COEN 313 - Advanced Computer Architecture","ForeignCourseID":115,"ForeignCourseName":"CSC 856 - Advanced Computer Architecture","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":41,"LocalCourseName":"COEN 315 - Web Architecture & Protocols","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":2,"Status":"accepted","LocalCourseID":42,"LocalCourseName":"COEN 317 - Distributed Systems","ForeignCourseID":17,"ForeignCourseName":"CMPE 227 - Distributed Systems","SchoolName":"San Jose State University"},
{"EquivID":44,"Status":"accepted","LocalCourseID":42,"LocalCourseName":"COEN 317 - Distributed Systems","ForeignCourseID":105,"ForeignCourseName":"CSC 835 - Distributed Systems","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":43,"LocalCourseName":"COEN 329 - Network Technology","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":44,"LocalCourseName":"COEN 331 - Wireless and Mobile Networks","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":45,"LocalCourseName":"COEN 332 - Wireless/Mobile Multimedia Networks","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":46,"LocalCourseName":"COEN 335 - High Performance Networking","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":47,"LocalCourseName":"COEN 338 - Image & Video Compression","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":48,"LocalCourseName":"COEN 340 - Digital Image Processing I","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":49,"LocalCourseName":"COEN 344 - Computer Vision I","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":50,"LocalCourseName":"COEN 348E - Speech Coding, Speech Recognition and Biometrics Applications of Signal Processing","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":45,"Status":"accepted","LocalCourseID":51,"LocalCourseName":"COEN 350 - Network Security","ForeignCourseID":7,"ForeignCourseName":"CMPE 209 - Network Security","SchoolName":"San Jose State University"},
{"EquivID":null,"Status":null,"LocalCourseID":52,"LocalCourseName":"COEN 351 - Internet & E-Commerce Security","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":7,"Status":"rejected","LocalCourseID":53,"LocalCourseName":"COEN 379 - Advanced Design and Analysis of Algorithms","ForeignCourseID":99,"ForeignCourseName":"CSC 810 - Analysis of Algorithms II","SchoolName":"San Francisco State University"},
{"EquivID":46,"Status":"accepted","LocalCourseID":54,"LocalCourseName":"COEN 380 - Advanced Database Systems","ForeignCourseID":94,"ForeignCourseName":"CSC 730 - Advanced Database Systems","SchoolName":"San Francisco State University"},
{"EquivID":47,"Status":"accepted","LocalCourseID":55,"LocalCourseName":"COEN 383 - Advanced Operating Systems","ForeignCourseID":93,"ForeignCourseName":"CSC 720 - Advanced Operating Systems","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":56,"LocalCourseName":"COEN 385 - Formal Methods in Software Engineering","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":57,"LocalCourseName":"COEN 386 - Software Architecture","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":58,"LocalCourseName":"COEN 396 - Advanced Topics in Computer Science and Engineering","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":59,"LocalCourseName":"COEN 485 - Software Engineering Capstone","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":60,"LocalCourseName":"COEN 493 - Directed Research","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":61,"LocalCourseName":"COEN 497 - Master's Thesis Res","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":62,"LocalCourseName":"COEN 498 - Phd Thesis Research","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":48,"Status":"rejected","LocalCourseID":63,"LocalCourseName":"COEN 499 - Independent Study","ForeignCourseID":131,"ForeignCourseName":"CSC 899 - Independent Study","SchoolName":"San Francisco State University"},
{"EquivID":null,"Status":null,"LocalCourseID":64,"LocalCourseName":"COEN 912C - Abstract Data Types & Structures","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":65,"LocalCourseName":"COEN 920C - Embedded Systems and Assembly Language","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null},
{"EquivID":null,"Status":null,"LocalCourseID":66,"LocalCourseName":"COEN 921C - Introduction to Logic Design","ForeignCourseID":null,"ForeignCourseName":null,"SchoolName":null}
];